Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
#Para imagenes
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('SkillsHub.urls')),
    path('cuentas/', include('django.contrib.auth.urls')),    
    path('api/v1/', include('api.urls', namespace='api')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SkillsHub/urls.py
from django.urls import path
from . import views
from .views import Servicios, ServicioNuevo, Detalles, Actualiza, Borra, RealizarCompra, Valoraciones, PerfilUsuario, lista_insignias
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required


urlpatterns = [
    path('', Servicios.as_view(), name='servicios'),
    path('nuevo_servicio/', login_required(ServicioNuevo.as_view()), name='nuevo_servicio'),
    path('detalles/<int:pk>/', Detalles.as_view(), name='detalles'),
    path('actualiza/<int:pk>/', login_required(Actualiza.as_view()), name='actualiza'),
    path('borra/<int:pk>/', login_required(Borra.as_view()), name='borra'),

    path('register/', views.register, name='register'),

    path('checkout/<int:pk>/', login_required(RealizarCompra.as_view()), name='checkout'),

    path('valoraciones/<int:pk>/', login_required(Valoraciones.as_view()), name='valoraciones'),

    path('perfil_usuario/<int:pk>/', login_required(PerfilUsuario.as_view()), name='perfil_usuario'),

    path('configura_perfil/', login_required(views.configura_perfil), name='configura_perfil'),

    path('buscar_usuario/', views.buscar_usuario, name='buscar_usuario'),

    path('gestion/', views.gestion, name='gestion'),
    path('top-vendedores/', staff_member_required(views.top_vendedores), name='top_vendedores'),
    path('top-compradores/', staff_member_required(views.top_compradores), name='top_compradores'),
    path('lista-reportes/', staff_member_required(views.lista_reportes), name='lista_reportes'),
    path('lista_usuarios/', staff_member_required(views.lista_usuarios), name='lista_usuarios'),

    path('rooms',  login_required(views.room), name="rooms"),

    path('chat/<slug:slug>/',  login_required(views.chatPage), name="chat"),

    path('iniciar_chat/<int:user_id>/', login_required(views.iniciar_chat), name='iniciar_chat'),

    path('reportar/<int:user_id>/', login_required(views.reportar_usuario), name='reportar'),
    path('error/', views.error, name='error'),

    path('seguir/<int:pk>/', views.seguir_usuario, name='seguir'),
    path('dejar_de_seguir/<int:pk>/', views.dejar_de_seguir_usuario, name='dejar_de_seguir'),
    path('seguidores/<int:pk>/', views.lista_seguidores, name='seguidores'),
    path('seguidos/<int:pk>/', views.lista_seguidos, name='seguidos'),

    path('lista_compras', login_required(views.lista_compras), name='lista_compras'),
    path('insignias/', login_required(views.lista_insignias), name='lista_insignias'),
    path('seleccionar_insignia_perfil/<int:insignia_id>/', login_required(views.seleccionar_insignia_perfil), name='seleccionar_insignia_perfil'),  
]

api/urls.py
from rest_framework import routers
from .views import ServicioViewSet

app_name = 'api'

router = routers.DefaultRouter()

router.register('servicio',ServicioViewSet, 'servicio_api')

urlpatterns = router.urls

SkillsHub/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

class Insignia(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    icono = models.ImageField(upload_to='insignias/')

class UsuarioInsignia(models.Model):
    usuario = models.ForeignKey('Usuario', on_delete=models.CASCADE)
    insignia = models.ForeignKey(Insignia, on_delete=models.CASCADE)
    desbloqueada = models.BooleanField(default=False)

class Usuario(AbstractUser):
    nombre = models.CharField(max_length=100) 
    saldo = models.DecimalField(max_digits=10, decimal_places=2, default=0, null=True)
    avatar = models.ImageField(upload_to='avatars/', default='avatars/perfil.png') 
    comentario = models.TextField(blank=True, null=True)
    baneado = models.BooleanField(default=False) 

    seguidores = models.ManyToManyField("self", symmetrical=False, related_name='usuarios_seguidores', blank=True)
    seguidos = models.ManyToManyField("self", symmetrical=False, related_name='usuarios_seguidos', blank=True)
    insignia_perfil = models.ForeignKey(UsuarioInsignia, null=True, blank=True, on_delete=models.SET_NULL, related_name='insignia_en_perfil')
    
    def __str__(self):
        return self.username

class Reporte(models.Model):
    usuario_reportado = models.ForeignKey(Usuario, related_name='reportes_recibidos', on_delete=models.CASCADE)
    reportador = models.ForeignKey(Usuario, related_name='reportes_enviados', on_delete=models.CASCADE)
    motivo = models.TextField()
    fecha = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Reporte de {self.usuario_reportado} por {self.reportador} el {self.fecha}"
    

class Ubicacion(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre
    
class Categoria(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Servicio(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    descripcion = models.TextField()
    ubicacion = models.ForeignKey(Ubicacion, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    activo = models.BooleanField(default=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='servicio/', blank=False, default='servicio/blanco.jpeg')

    def __str__(self):
        return(self.nombre)

class Compra(models.Model):
    usuario_comprador = models.ForeignKey(Usuario, related_name='compras_realizadas', on_delete=models.CASCADE)
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE)
    fecha = models.DateTimeField(default=timezone.now) #Hacemos que automaticamente se ponga como fecha y hora actual
    valoracion = models.TextField(blank=True, null=True)
    puntuacion = models.IntegerField(default=0, choices=[(i, i) for i in range(6)]) #Que el rango de puntuacion sea del 0-5
    usuario_vendedor = models.ForeignKey(Usuario, related_name='ventas_realizadas', on_delete=models.CASCADE) 
    #Se pone related_name ya que no se puede poner dos FK iguales sobre el mismo modelo ya que chocan, asi se distinguen

class Meta:
    unique_together = ('usuario', 'servicio', 'fecha')

class Room(models.Model):
    name=models.CharField(max_length=20)
    slug = models.SlugField(max_length=20, unique=True)  # id sala unico
    usuarios = models.ManyToManyField(Usuario, related_name='rooms')  # para adjudicar sala a los usuarios y poder filtrar 

    def __str__(self):
        return(self.name)

class Mensaje(models.Model):
    content=models.TextField()
    usuario=models.ForeignKey(Usuario,on_delete=models.CASCADE)
    room=models.ForeignKey(Room,on_delete=models.CASCADE)
    created_on=models.DateTimeField(default=timezone.now) 

SkillsHub/views.py
from django.shortcuts import render,  get_object_or_404, redirect
from .models import Usuario, Compra, Servicio, Room, Mensaje, Reporte, Ubicacion, UsuarioInsignia, Insignia, Categoria
from django.views import View
from django.views.generic import ListView, DetailView
from .forms import ServicioForm, ValoracionForm, RegisterForm, PerfilForm, FiltroCategoria, FiltroUbicacion, ReporteForm
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.utils import timezone
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.db import models
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.db.models import Q


# Create your views here.

class Servicios(ListView):
    template_name = 'Proyecto/servicios.html'
    model = Servicio
    form_class_categoria = FiltroCategoria
    form_class_ubicacion = FiltroUbicacion

    def get_queryset(self):
        queryset = Servicio.objects.filter(activo=True)
        categoria = self.request.GET.get('categoria', None)
        ubicacion = self.request.GET.get('ubicacion', None)  

        if categoria:
            queryset = queryset.filter(categoria=categoria)

        if ubicacion:
            queryset = queryset.filter(ubicacion=ubicacion)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_categoria'] = self.form_class_categoria(initial={'categoria': self.request.GET.get('categoria', None)})
        context['form_ubicacion'] = self.form_class_ubicacion(initial={'ubicacion': self.request.GET.get('ubicacion', None)}) 
        return context

class ServicioNuevo(CreateView):
    model = Servicio
    form_class = ServicioForm
    template_name = 'Proyecto/nuevo_servicio.html'
    success_url = reverse_lazy('servicios')

    def form_valid(self, form): 
        form.instance.usuario = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categorias'] = Categoria.objects.all()
        context['ubicaciones'] = Ubicacion.objects.all()  # Obtener todas las ubicaciones disponibles
        return context

class Detalles(DetailView):
    model = Servicio
    template_name = 'Proyecto/detalles.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
       
        if self.request.user.is_authenticated: #Verifica si el usuario está autenticado
            servicio = self.get_object()
            existeValoracion = False

            compras = servicio.compra_set.all() #Comprueba todas las compras que hay de ese servicio
            for compra in compras:
                if compra.valoracion:
                    existeValoracion = True
                    break

            #Vemos las compras que tiene el usuario actual y si hay alguna de este servicio
            compras_usuario = Compra.objects.filter(usuario_comprador=self.request.user, servicio=servicio)
            ha_realizado_compra = compras_usuario.exists()

            context['ha_realizado_compra'] = ha_realizado_compra
            context['existeValoracion'] = existeValoracion  # Para mostrar todas las valoraciones
        return context


class Actualiza(UpdateView):
    model = Servicio
    form_class = ServicioForm
    template_name = 'Proyecto/actualiza.html'
    success_url = reverse_lazy('servicios')

    def get_queryset(self):
        queryset = super().get_queryset()
        user = self.request.user
        if user.is_authenticated:
            if user.is_superuser:
                return queryset.all() 
            else:
                return queryset.filter(usuario=user) 
        else:
            return queryset.none()  

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categorias'] = Categoria.objects.all()  # Agrega todas las categorías al contexto
        context['ubicaciones'] = Ubicacion.objects.all()  # Agrega todas las ubicaciones al contexto
        return context

class Borra(DeleteView):
    model = Servicio
    template_name = 'Proyecto/borra.html'
    success_url = reverse_lazy('servicios')

    def get_queryset(self):
        queryset = super().get_queryset()
        user = self.request.user
        if user.is_authenticated:
            if user.is_superuser:
                return queryset.all() # Si el usuario es administrador, devuelve todos los objetos
            else:
                return queryset.filter(usuario=user)  # Si el usuario no es administrador, filtra por el usuario actual
        else:
            return queryset.none() # Si el usuario no está autenticado, devuelve un queryset vacío

class RealizarCompra(View): #Como tanto fecha como fecha_limite de valoracion son automaticas desde el modelo no hay que calcular nada
    template_name = "Proyecto/checkout.html"

    def get(self, request, pk):
        servicio = get_object_or_404(Servicio, pk=pk)
        return render(request, self.template_name, {'servicio': servicio})

    def post(self, request, pk):
        servicio = Servicio.objects.get(pk=pk)
        usuario_comprador = request.user
        usuario_vendedor = servicio.usuario

        # El mismo usuario no puede comprarse a si mismo SE PODRIA QUITAR EL "COMPRAR DIRECTAMENTE"
        if servicio.usuario == usuario_comprador:
            messages.error(request, 'No puedes comprar tu propio servicio.')
            return redirect('detalles', pk=pk) #detalles del servicio

        # Si el servicio esta desactivado que no pueda comprarlo SE PODRIA QUITAR EL "COMPRAR DIRECTAMENTE"
        if not servicio.activo:
            messages.error(request, 'Este servicio está desactivado y no se puede comprar.')
            return redirect('detalles', pk=pk) #detalles del servicio

        # Comprobar que tiene suficiente saldo
        if usuario_comprador.saldo < servicio.precio:
            messages.error(request, 'No tienes suficiente saldo para realizar esta compra. Para meter dinero ve a configuración en tu perfil.')
            return redirect('detalles', pk=pk) #detalles del servicio

        compra = Compra(usuario_comprador=usuario_comprador, servicio=servicio, usuario_vendedor=usuario_vendedor)
        compra.save()

        usuario_comprador.saldo -= servicio.precio
        usuario_comprador.save()
        usuario_vendedor.saldo += servicio.precio
        usuario_vendedor.save()

        messages.success(request, '¡La compra se ha realizado con éxito!, puedes dejar una valoración después de una semana')
        return redirect('servicios')


class Valoraciones(UpdateView):
    model = Compra
    form_class = ValoracionForm
    template_name = 'Proyecto/valoraciones.html'
    success_url = reverse_lazy('detalles')

    def get(self, request, pk):
        servicio = get_object_or_404(Servicio, pk=pk)
        usuario_actual = request.user
        compra = Compra.objects.filter(servicio=servicio, usuario_comprador=usuario_actual).first()
        if compra:
            if compra.fecha > timezone.now():
                messages.error(request, "La fecha límite para valorar este servicio aún no ha pasado.")
                return redirect('detalles', pk=pk)
            form = ValoracionForm(instance=compra)
            return render(request, self.template_name, {'servicio': servicio, 'compra': compra, 'form': form})
        else:
            return redirect('detalles', pk=pk)

    def post(self, request, pk):
        servicio = get_object_or_404(Servicio, pk=pk)
        usuario_actual = request.user
        compra = Compra.objects.filter(servicio=servicio, usuario_comprador=usuario_actual).first()
        if compra and compra.fecha <= timezone.now():
            form = self.form_class(request.POST, instance=compra)
            if form.is_valid():
                form.save()
                return redirect('detalles', pk=pk)
        return redirect('detalles', pk=pk)



def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registrado con éxito")
            return redirect("/")
    else:
        form = RegisterForm()

    return render(request, "registration/register.html", {"form": form})


def configura_perfil(request):
    perfil_usuario = request.user

    if request.user == perfil_usuario:
        if request.method == 'POST':
            form = PerfilForm(request.POST, request.FILES, instance=request.user)
            if form.is_valid():
                pk = request.user.pk
                form.save()
                return redirect('perfil_usuario', pk=pk)  
        else:
            form = PerfilForm(instance=request.user)
        return render(request, 'Proyecto/configura_perfil.html', {'form': form})
    else:
        return render(request, 'Proyecto/perfil_usuario.html')

class PerfilUsuario(LoginRequiredMixin, View):
    template_name = 'Proyecto/perfil_usuario.html'

    def get(self, request, pk):
        usuario = get_object_or_404(Usuario, pk=pk)
        servicios = Servicio.objects.filter(usuario=usuario)
        compras_realizadas = Compra.objects.filter(usuario_comprador=usuario)

        if request.user == usuario:
            permitir_configuracion = True
            compras_realizadas = Compra.objects.filter(usuario_comprador=usuario)
        else:
            permitir_configuracion = False
            compras_realizadas = None

        seguidores = usuario.usuarios_seguidores.all()
        seguidos = usuario.usuarios_seguidos.all()

        context = {
            'usuario': usuario,
            'servicios': servicios,

SkillsHub/templates/Proyecto/actualiza.html
{% extends './base.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="display-4">Actualizar Servicio</h1>

    <div class="card mb-3">
        <div class="card-body">
            <form method="post" action="{% url 'actualiza' pk=servicio.pk %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                        <div class="form-group m-3">
                            <label for="id_nombre">Nombre</label>
                            <input type="text" class="form-control" id="id_nombre" name="nombre" placeholder="Nombre" pattern="^[A-Za-zñÑáéíóúÁÉÍÓÚ0-9 .,]*$" value="{{ servicio.nombre }}" required oninput="validarFormulario()">
                            <div class="invalid-feedback">El nombre debe comenzar con una letra y no debe contener caracteres especiales o números.</div>
                        </div>
                        <div class="form-group m-3">
                            <label for="id_precio">Precio</label>
                            <input type="number" class="form-control" id="id_precio" name="precio" placeholder="Precio" value="{{ servicio.precio|stringformat:"s" }}" required min="0" step="0.01" oninput="validarFormulario()">
                            <div class="invalid-feedback">El precio debe ser un número mayor que cero.</div>
                        </div> 
                        <div class="form-group m-3">
                            <label for="id_descripcion">Descripción</label>
                            <textarea class="form-control" id="id_descripcion" name="descripcion" rows="3" placeholder="Descripción" required oninput="validarFormulario()">{{ servicio.descripcion }}</textarea>
                            <div class="invalid-feedback">La descripción no debe contener caracteres especiales.</div>
                        </div>
                        <div class="form-group m-3">
                            <label for="id_categoria">Categoría</label>
                            <select class="form-control" id="id_categoria" name="categoria" required>
                                <option value="{{ servicio.categoria.id }}" selected>{{ servicio.categoria.nombre }}</option>
                                {% for categoria in categorias %}
                                    <option value="{{ categoria.id }}">{{ categoria.nombre }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="form-group m-3">
                            <label for="id_ubicacion">Ubicación</label>
                            <select class="form-control" id="id_ubicacion" name="ubicacion" required>
                                <option value="{{ servicio.ubicacion.id }}" selected>{{ servicio.ubicacion.nombre }}</option>
                                {% for ubicacion in ubicaciones %}
                                    <option value="{{ ubicacion.id }}">{{ ubicacion.nombre }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        
                        <div class="form-group m-3">
                            <label for="id_activo">Activo</label>
                            <input type="checkbox" class="form-check-input" id="id_activo" name="activo" {% if servicio.activo %}checked{% endif %}>
                            <label class="form-check-label" for="id_activo">Activo</label>
                        </div>
                        <div class="form-group m-3">
                            <label for="id_imagen">Imagen</label>
                            <input type="file" class="form-control-file w-100" id="id_imagen" name="imagen">
                            {% if servicio.imagen %}
                                <img src="{{ servicio.imagen.url }}" alt="Imagen" class="mt-2" style="max-width: 150px;">
                            {% endif %}
                        </div>                
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 text-center">
                        <button type="submit" class="btn btn-success" id="botonActualizar">Actualizar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <script>
        function validarCampo(campo, expresionRegular, mensajeError) {
            var valorCampo = campo.value;
            var expresion = new RegExp(expresionRegular);
    
            if (!expresion.test(valorCampo)) {
                campo.setCustomValidity(mensajeError);
                campo.classList.add('is-invalid');
                return false;
            } else {
                campo.setCustomValidity('');
                campo.classList.remove('is-invalid');
                return true;
            }
        }
    
        function validarFormulario() {
            var nombreValido = validarCampo(
                document.getElementById('id_nombre'), 
                '^[A-Za-zñÑáéíóúÁÉÍÓÚ][A-Za-zñÑáéíóúÁÉÍÓÚ ]*$', 
                'El nombre debe comenzar con una letra y no debe contener caracteres especiales o números.'
            );
            var precioValido = validarCampo(
                document.getElementById('id_precio'), 
                '^[0-9]+(?:\\.[0-9]{1,2})?$', 
                'El precio debe ser un número mayor que cero.'
            );
            var descripcionValida = validarCampo(
                document.getElementById('id_descripcion'), 
                '^[A-Za-z0-9ñÑáéíóúÁÉÍÓÚ .,]*$', 
                'La descripción no debe contener caracteres especiales.'
            );
    
            var botonActualizar = document.getElementById('botonActualizar');
            botonActualizar.disabled = !(nombreValido && precioValido && descripcionValida);
        }
    
        document.addEventListener('DOMContentLoaded', function() {
            validarFormulario();
        });
    </script>
</div>
{% endblock %}

SkillsHub/templates/Proyecto/configura_perfil.html
{% extends './base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card mb-3">
                <div class="card-header">
                    <h1 class="card-title">Perfil de Usuario</h1>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data" oninput="validarFormulario()">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_saldo">Saldo</label>
                            <input type="number" class="form-control" id="id_saldo" name="saldo" step="0.01" placeholder="Ingresa tu saldo" value="{{ user.saldo|stringformat:"s" }}" oninput="validarCampo(this, '^[0-9]+(\\.[0-9]{1,2})?$', 'El saldo debe ser un número válido.')">
                            <div class="invalid-feedback">El saldo debe ser un número válido.</div>
                        </div><br>
                        <div class="form-group">
                            <label for="id_comentario">Comentario</label>
                            <textarea class="form-control" id="id_comentario" name="comentario" rows="3" placeholder="Ingresa una descripción" oninput="validarCampo(this, '^[A-Za-zñÑáéíóúÁÉÍÓÚ0-9 .,]*$', 'El comentario no debe contener caracteres especiales.')">{{ user.comentario|default_if_none:"" }}</textarea>
                            <div class="invalid-feedback">El comentario no debe contener caracteres especiales.</div>
                        </div><br>
                        <div class="form-group">
                            <label for="id_avatar">Avatar</label>
                            <input type="file" class="form-control-file w-100" id="id_avatar" name="avatar">
                            {% if user.avatar %}
                                <img src="{{ user.avatar.url }}" alt="Avatar" class="mt-2" style="max-width: 150px;">
                            {% endif %}
                        </div><br>
                        <div class="text-center mt-3">
                            <button type="submit" class="btn btn-success" id="botonGuardar" disabled>Guardar Cambios</button>
                            <a href="{% url 'perfil_usuario' user.pk %}" class="btn btn-secondary">Volver al perfil</a>
                        </div><br>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function validarCampo(campo, expresionRegular, mensajeError) {
        var valorCampo = campo.value;
        var expresion = new RegExp(expresionRegular);

        if (valorCampo.trim() !== '' && !expresion.test(valorCampo)) {
            campo.setCustomValidity(mensajeError);
            campo.classList.add('is-invalid');
            return false;
        } else {
            campo.setCustomValidity('');
            campo.classList.remove('is-invalid');
            return true;
        }
    }

    function validarFormulario() {
        var saldoValido = validarCampo(document.getElementById('id_saldo'), '^[0-9]+(\\.[0-9]{1,2})?$', 'El saldo debe ser un número válido.');
        var comentarioValido = validarCampo(document.getElementById('id_comentario'), '^[A-Za-zñÑáéíóúÁÉÍÓÚ0-9 .,]*$', 'El comentario no debe contener caracteres especiales.');

        var botonGuardar = document.getElementById('botonGuardar');
        botonGuardar.disabled = !(saldoValido && comentarioValido);
    }
</script>

{% endblock %}

SkillsHub/templates/Proyecto/nuevo_servicio.html
{% extends './base.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="display-4">Nuevo Servicio</h1>

    <div class="card">
        <div class="card-body">
            <form method="post" action="{% url 'nuevo_servicio' %}" enctype="multipart/form-data" oninput="validarFormulario()">
                {% csrf_token %}
                <div class="form-group m-3">
                    <label for="id_nombre">Nombre</label>
                    <input type="text" class="form-control" id="id_nombre" name="nombre" placeholder="Nombre" required pattern="^[A-Za-zñÑáéíóúÁÉÍÓÚ0-9 .,]*$">
                    <div class="invalid-feedback">El nombre debe comenzar con una letra y no debe contener caracteres especiales.</div>
                </div>
                <div class="form-group m-3">
                    <label for="id_precio">Precio</label>
                    <input type="number" class="form-control" id="id_precio" name="precio" placeholder="Precio" required min="0" step="0.01">
                    <div class="invalid-feedback">El precio debe ser un número mayor que cero.</div>
                </div>
                <div class="form-group m-3">
                    <label for="id_descripcion">Descripción</label>
                    <textarea class="form-control" id="id_descripcion" name="descripcion" rows="3" placeholder="Descripción" required pattern="^[A-Za-zñÑáéíóúÁÉÍÓÚ0-9 .,]*$"></textarea>
                    <div class="invalid-feedback">La descripción no debe contener caracteres especiales.</div>
                </div>
                <div class="form-group m-3">
                    <label for="id_categoria">Categoría</label>
                    <select class="form-control" id="id_categoria" name="categoria" required>
                        <option value="" selected>Seleccione una categoría</option>
                        {% for categoria in categorias %}
                            <option value="{{ categoria.id }}">{{ categoria.nombre }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group m-3">
                    <label for="id_ubicacion">Ubicación</label>
                    <select class="form-control" id="id_ubicacion" name="ubicacion" required>
                        <option value="" selected>Seleccione una ubicación</option>
                        {% for ubicacion in ubicaciones %}
                            <option value="{{ ubicacion.id }}">{{ ubicacion.nombre }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group m-3">
                    <label for="id_activo">Activo</label>
                    <input type="checkbox" class="form-check-input" id="id_activo" name="activo">
                    <label class="form-check-label" for="id_activo"></label>
                </div>
                <div class="form-group m-3">
                    <label for="id_imagen">Imagen</label>
                    <input type="file" class="form-control-file w-100" id="id_imagen" name="imagen">
                </div>
                <div class="row">
                    <div class="col-12 text-center">
                        <button type="submit" class="btn btn-success" id="botonPublicar">Publicar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <script>
        function validarCampo(campo, expresionRegular) {
            var valorCampo = campo.value;
            var expresion = new RegExp(expresionRegular);

            if (valorCampo.trim() !== '' && !expresion.test(valorCampo)) {
                campo.setCustomValidity("Inválido");
                campo.classList.add('is-invalid');
                return false;
            } else {
                campo.setCustomValidity('');
                campo.classList.remove('is-invalid');
                return true;
            }
        }

        function validarFormulario() {
            var nombreValido = validarCampo(document.getElementById('id_nombre'), '^[A-Za-zñÑáéíóúÁÉÍÓÚ][A-Za-zñÑáéíóúÁÉÍÓÚ ]*$');
            var precioValido = validarCampo(document.getElementById('id_precio'), '^[0-9]+(\\.[0-9]{1,2})?$');
            var descripcionValida = validarCampo(document.getElementById('id_descripcion'), '^[A-Za-zñÑáéíóúÁÉÍÓÚ0-9 .,]*$');

            var botonPublicar = document.getElementById('botonPublicar');
            botonPublicar.disabled = !(nombreValido && precioValido && descripcionValida);
        }

        document.addEventListener('DOMContentLoaded', function() {
            validarFormulario();
        });
    </script>

</div>
{% endblock %}